server:
  port: 8081

spring:
  application:
    name: order_management_system

  profiles:
    include:
      - db

# Liquibase configuration
  liquibase:
    change-log: db/changelog/master-changelog.yaml
    url: jdbc:mysql://localhost:3306/ORDERS_MANAGEMENT_SYSTEM
    user: root
    password: 123456
    enabled: true
    contexts: local